---
apiVersion: v1
kind: Service
metadata:
  name: my-image
spec:
  type: LoadBalancer
  selector:
    app: my-image
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image
  labels:
    app: my-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-image
  template:
    metadata:
      labels:
        app: my-image
    spec:
      containers:
      - name: my-image
        image: us-central1-docker.pkg.dev/astute-azimuth-453510-b8/action123/my-image:${{ github.sha }}
