version: 2
updates:
  - package-ecosystem: "maven"    # Use 'maven' if you are using Maven; for Gradle, use 'gradle'
    directory: "/"                 # The directory where your pom.xml or build.gradle is located
    schedule:
      interval: "weekly"           # Set to "daily", "weekly", or "monthly" for update frequency
    commit-message:
      prefix: "chore"              # Prefix for commit message
    versioning-strategy: "increase" # Options: "increase", "lockfile-only", "auto", " widen"
  - package-ecosystem: "gradle"   # If using Gradle instead of Maven
    directory: "/"                 # Directory with build.gradle
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    versioning-strategy: "increase"
